### ISSUE TITLE
[RFC]向git介绍章节中加入github-cli的介绍

### ISSUE THREAD

**Issue by schulice** [SCUTOSC/MSCTutorial#5]
# 主要问题
在新的github界面中对ssh密钥的权限管理有些复杂，可否介绍使用github-cli来进行github认证的方法。
# 相关资料
gh中文手册 https://zhangzhanhaoxiang.github.io/github-cli-manual-zh/gh_auth.html

**Comment by fslongjin** [comment]
ssh配公钥不难哈哈。
增加ghcli的教程无问题，尽管我平时不怎么使用这种哈哈哈

**Comment by schulice** [comment]
> ssh配公钥不难哈哈。 增加ghcli的教程无问题，尽管我平时不怎么使用这种哈哈哈

这个只是个人习惯，之前用ssh指定半年到期时发了好几封邮件提醒我，有点烦。
再打扰下，问下任务书后面有那些内容，我已经在wsl2上用了一段时间的arch了，wsl2有完整内核，也可以用systemctl，和vm主要区别应该只是没有一个固定的内网ip和微软自己缝合的wslg（或许）？请教下有无必要再换到vm上。

**Comment by fslongjin** [comment]
那无所谓啊哈哈哈。
后面的话打算整一下DragonOS相关的实验。
由于DragonOS目前自动安装环境的脚本（bootstrap.sh）还没有适配arch linux的包管理器。不知道有无兴趣完善一下那个脚本？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月1日(周日) 凌晨0:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SCUTOSC/MSCTutorial] [RFC]向git介绍章节中加入github-cli的介绍 (Issue #5)




  
ssh配公钥不难哈哈。 增加ghcli的教程无问题，尽管我平时不怎么使用这种哈哈哈
  
这个只是个人习惯，之前用ssh指定半年到期时发了好几封邮件提醒我，有点烦。
 再打扰下，问下任务书后面有那些内容，我已经在wsl2上用了一段时间的arch了，wsl2有完整内核，也可以用systemctl，和vm主要区别应该只是没有一个固定的内网ip和微软自己缝合的wslg（或许）？请教下有无必要再换到vm上。

**Comment by schulice** [comment]
> 那无所谓啊哈哈哈。 后面的话打算整一下DragonOS相关的实验。 由于DragonOS目前自动安装环境的脚本（bootstrap.sh）还没有适配arch linux的包管理器。不知道有无兴趣完善一下那个脚本？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月1日(周日) 凌晨0:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [SCUTOSC/MSCTutorial] [RFC]向git介绍章节中加入github-cli的介绍 (Issue #5) ssh配公钥不难哈哈。 增加ghcli的教程无问题，尽管我平时不怎么使用这种哈哈哈 这个只是个人习惯，之前用ssh指定半年到期时发了好几封邮件提醒我，有点烦。 再打扰下，问下任务书后面有那些内容，我已经在wsl2上用了一段时间的arch了，wsl2有完整内核，也可以用systemctl，和vm主要区别应该只是没有一个固定的内网ip和微软自己缝合的wslg（或许）？请教下有无必要再换到vm上。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好好好，等文档出来看下。
